server:
  port: 8989

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
